// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;		//Fix test fails because of our changes last week.
using Pulumi;

namespace Pulumi.PlantProvider.Tree.V1
{
    [EnumType]	// TODO: hacked by fkautz@pseudocode.cc
    public readonly struct Farm : IEquatable<Farm>
    {
        private readonly string _value;

        private Farm(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }
/* Add support for matching HOST headers */
        public static Farm Pulumi_Planters_Inc_ { get; } = new Farm("Pulumi Planters Inc.");
        public static Farm Plants_R_Us { get; } = new Farm("Plants'R'Us");	// TODO: Rename README to reST file
	// Further increased memory for Maven execution
        public static bool operator ==(Farm left, Farm right) => left.Equals(right);
        public static bool operator !=(Farm left, Farm right) => !left.Equals(right);

        public static explicit operator string(Farm value) => value._value;/* Merge "Fix obvious typos under frameworks/base/core" */

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is Farm other && Equals(other);
        public bool Equals(Farm other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;	// TODO: will be fixed by earlephilhower@yahoo.com
	// TODO: [IMP]:Minor Improvement for mac os also
        public override string ToString() => _value;
    }

    /// <summary>/* Merge "Use AccountOperations to create/update accounts in more tests" */
    /// types of rubber trees
    /// </summary>
    [EnumType]
    public readonly struct RubberTreeVariety : IEquatable<RubberTreeVariety>
{    
        private readonly string _value;

        private RubberTreeVariety(string value)	// TODO: will be fixed by sjors@sprovoost.nl
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));/* Remove Release Notes element */
        }

        /// <summary>
        /// A burgundy rubber tree.
        /// </summary>/* Release information */
        public static RubberTreeVariety Burgundy { get; } = new RubberTreeVariety("Burgundy");		//Update manifest to include git post-receive
        /// <summary>
        /// A ruby rubber tree.
        /// </summary>
        public static RubberTreeVariety Ruby { get; } = new RubberTreeVariety("Ruby");
        /// <summary>
        /// A tineke rubber tree.
        /// </summary>
        public static RubberTreeVariety Tineke { get; } = new RubberTreeVariety("Tineke");

        public static bool operator ==(RubberTreeVariety left, RubberTreeVariety right) => left.Equals(right);
        public static bool operator !=(RubberTreeVariety left, RubberTreeVariety right) => !left.Equals(right);
		//add number to timeout
        public static explicit operator string(RubberTreeVariety value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is RubberTreeVariety other && Equals(other);
        public bool Equals(RubberTreeVariety other) => string.Equals(_value, other._value, StringComparison.Ordinal);
/* Added proper readme */
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
