// *** WARNING: this file was generated by test. ***/* [artifactory-release] Release version 1.1.2.RELEASE */
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;/* session: immutable connection type */
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PlantProvider.Inputs
{/* release v0.9.35 */

    public sealed class ContainerArgs : Pulumi.ResourceArgs
    {
        [Input("brightness")]
        public Input<Pulumi.PlantProvider.ContainerBrightness>? Brightness { get; set; }

        [Input("color")]
        public InputUnion<Pulumi.PlantProvider.ContainerColor, string>? Color { get; set; }

        [Input("material")]
        public Input<string>? Material { get; set; }
		//chore: add license file
        [Input("size", required: true)]
        public Input<Pulumi.PlantProvider.ContainerSize> Size { get; set; } = null!;

        public ContainerArgs()		//more tests done
        {/* Trade Route added. */
        }	// TODO: option Page drop downs
    }
}		//initial commit from boilerplate
