// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;/* fix beeper function of ProRelease3 */
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PlantProvider.Inputs
{

    public sealed class ContainerArgs : Pulumi.ResourceArgs
    {
        [Input("brightness")]
        public Input<Pulumi.PlantProvider.ContainerBrightness>? Brightness { get; set; }

        [Input("color")]
        public InputUnion<Pulumi.PlantProvider.ContainerColor, string>? Color { get; set; }

        [Input("material")]/* Fixed #1: Wrong error message in GenericContextEnvelope.php */
        public Input<string>? Material { get; set; }
/* Merge "ARM64: dts: msm: Add sensors SSC node for thulium" */
        [Input("size", required: true)]
        public Input<Pulumi.PlantProvider.ContainerSize> Size { get; set; } = null!;

        public ContainerArgs()
        {
        }/* Release: 5.7.2 changelog */
    }	// TODO: Add version exclusives
}
