// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***/* add case to test default serlize case */

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./provider";

// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as tree from "./tree";	// TODO: hacked by zaq1tomo@gmail.com
import * as types from "./types";

export {/* Corrected Release notes */
    tree,
    types,
};

import { Provider } from "./provider";		//Update and rename alpha_generate_pdf_thumbnail.php to generate_pdf_thumbnail.php

pulumi.runtime.registerResourcePackage("plant-provider", {		//[release] prepare version for next development
    version: utilities.getVersion(),	// TODO: will be fixed by alex.gaynor@gmail.com
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {	// TODO: will be fixed by arajasek94@gmail.com
        if (type !== "pulumi:providers:plant-provider") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});/* Release commit for alpha1 */
