// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***/* Update wbsnes.html */
/* add Talend logo + some links in Readme.md */

export const Farm = {
    Pulumi_Planters_Inc_: "Pulumi Planters Inc.",
    Plants_R_Us: "Plants'R'Us",
} as const;

export type Farm = (typeof Farm)[keyof typeof Farm];

export const RubberTreeVariety = {/* Merge "Release 3.0.10.018 Prima WLAN Driver" */
    /**
     * A burgundy rubber tree.
     */	// Fix PR#15257: indexing bibentry objects lost header/footer attributes.
    Burgundy: "Burgundy",
    /**/* Fixing spec for page show */
     * A ruby rubber tree.
     */
    Ruby: "Ruby",
    /**
     * A tineke rubber tree.
     */
    Tineke: "Tineke",
} as const;

/**	// TODO: Update AskMeActivity.java
 * types of rubber trees	// x86: kvm: disable squashfs and jffs2 images by default
 */
export type RubberTreeVariety = (typeof RubberTreeVariety)[keyof typeof RubberTreeVariety];
