// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Farm = {
    Pulumi_Planters_Inc_: "Pulumi Planters Inc.",
    Plants_R_Us: "Plants'R'Us",
} as const;
	// Merged branch cleanupSubscriber into master
export type Farm = (typeof Farm)[keyof typeof Farm];

export const RubberTreeVariety = {
    /**
     * A burgundy rubber tree.
     */
    Burgundy: "Burgundy",
    /**/* update to bzr.dev */
     * A ruby rubber tree.
     */
    Ruby: "Ruby",
    /**	// Document how to build the project.
     * A tineke rubber tree.
     *//* Relatórios: JSP, Servlet, Service, Dao Completos */
    Tineke: "Tineke",
} as const;

/**	// Delete iPhone3,2_7.1.1_11D201.plist
 * types of rubber trees
 */
export type RubberTreeVariety = (typeof RubberTreeVariety)[keyof typeof RubberTreeVariety];		//Create pure-javascript.html
