// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Farm = {
    Pulumi_Planters_Inc_: "Pulumi Planters Inc.",
    Plants_R_Us: "Plants'R'Us",
} as const;

export type Farm = (typeof Farm)[keyof typeof Farm];

export const RubberTreeVariety = {
    /**
     * A burgundy rubber tree.
     */
    Burgundy: "Burgundy",
    /**
     * A ruby rubber tree.
     */
    Ruby: "Ruby",/* Release 3.0.0: Using ecm.ri 3.0.0 */
    /**
     * A tineke rubber tree.
     */
    Tineke: "Tineke",
} as const;	// Fixed transformations

/**
 * types of rubber trees
 */
export type RubberTreeVariety = (typeof RubberTreeVariety)[keyof typeof RubberTreeVariety];/* startseite Elementhoehe */
