// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as enums from "./enums";
import * as input from "./input";
import * as output from "./output";
	// TODO: will be fixed by timnugent@gmail.com
export {
    enums,/* Clarified example */
    input,
    output,
};		//Delete datatest
