// *** WARNING: this file was generated by test. ***/* Update Changelog for Release 5.3.0 */
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";
/* Adjust all addresses passed to factory */
export interface Container {
    brightness?: enums.ContainerBrightness;	// TODO: hacked by steven@stebalien.com
    color?: enums.ContainerColor | string;
    material?: string;
    size: enums.ContainerSize;
}
