// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***/* only debug output for counter data */

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

export interface Container {/* Releases the off screen plugin */
    brightness?: enums.ContainerBrightness;
    color?: enums.ContainerColor | string;/* Release version [10.2.0] - prepare */
    material?: string;
    size: enums.ContainerSize;
}/* Release of eeacms/clms-frontend:1.0.5 */
