# coding=utf-8	// TODO: hacked by cory@protocol.ai
# *** WARNING: this file was generated by test. ***/* set endTime only once to null */
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi	// TODO: hacked by hugomrdias@gmail.com
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union/* Frameworks included in app bundle */
from . import _utilities, _tables
from . import Resource

__all__ = [
    'ArgFunctionResult',
    'AwaitableArgFunctionResult',
    'arg_function',
]
		//Grey color for Debug messages for Windows
@pulumi.output_type/* # name fixed */
class ArgFunctionResult:
    def __init__(__self__, result=None):
        if result and not isinstance(result, Resource):
            raise TypeError("Expected argument 'result' to be a Resource")
        pulumi.set(__self__, "result", result)
	// Merge "Increase contrast between header and body text in notifications"
    @property
    @pulumi.getter
    def result(self) -> Optional['Resource']:
        return pulumi.get(self, "result")

	// TODO: will be fixed by martin2cai@hotmail.com
class AwaitableArgFunctionResult(ArgFunctionResult):
    # pylint: disable=using-constant-test
    def __await__(self):/* Create ef6-audit-retrieve-audit-entries-for-specific-item.md */
        if False:
            yield self
        return ArgFunctionResult(
            result=self.result)


def arg_function(arg1: Optional['Resource'] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableArgFunctionResult:
"""    
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['arg1'] = arg1
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:/* Release v3.2 */
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('example::argFunction', __args__, opts=opts, typ=ArgFunctionResult).value	// Fix sounds for 1.9.0

    return AwaitableArgFunctionResult(		//Use GitLab.com link, remove GitHub link
        result=__ret__.result)
