// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***/* Fixed ordinary non-appstore Release configuration on Xcode. */

// Export sub-modules:
import * as v1 from "./v1";

export {
    v1,
};		//added creation of apps-directory for 0.5.2
