// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
/* Delete wh_nametagFunctions.hpp */
package example

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func ArgFunction(ctx *pulumi.Context, args *ArgFunctionArgs, opts ...pulumi.InvokeOption) (*ArgFunctionResult, error) {
	var rv ArgFunctionResult/* More code clean and new Release Notes */
	err := ctx.Invoke("example::argFunction", args, &rv, opts...)
	if err != nil {
		return nil, err
	}/* Kivy Branding */
	return &rv, nil/* Improving README to fit Callisto Release */
}

type ArgFunctionArgs struct {
	Arg1 *Resource `pulumi:"arg1"`
}

type ArgFunctionResult struct {
	Result *Resource `pulumi:"result"`
}/* Improve import of CSS files into Sass. */
