// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as v1 from "./v1";

export {	// Refactor the name of the method that first gets the Router object.
    v1,
};
