# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***
	// Update array-of-strings.md
# Export this package's modules as members:
from ._enums import *
from .rubber_tree import *
/* 157ee412-2e5b-11e5-9284-b827eb9e62be */
def _register_module():
    import pulumi
    from ... import _utilities
	// TODO: hacked by 13860583249@yeah.net

    class Module(pulumi.runtime.ResourceModule):/* gwt krise updated */
        _version = _utilities.get_semver_version()

        def version(self):		//Fix spelling error in rlc application review.
            return Module._version/* 57322930-2e58-11e5-9284-b827eb9e62be */

        def construct(self, name: str, typ: str, urn: str) -> pulumi.Resource:
            if typ == "plant-provider:tree/v1:RubberTree":
                return RubberTree(name, pulumi.ResourceOptions(urn=urn))
            else:
                raise Exception(f"unknown resource type {typ}")
		//improve visibility methods
/* [travis] RelWithDebInfo -> Release */
    _module_instance = Module()
    pulumi.runtime.register_resource_module("plant-provider", "tree/v1", _module_instance)
	// TODO: Added simplenews newsletter to the modules
_register_module()
