# coding=utf-8		//(HTMLCanvasElement) : Add to the interface database for the sample.
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum
/* Move docker row schemes to schemes folder */
__all__ = [
    'Farm',
    'RubberTreeVariety',
]

/* [maven-release-plugin] rollback the release of latex-maven-1.0 */
class Farm(str, Enum):
    PULUMI_PLANTERS_INC_ = "Pulumi Planters Inc."/* File Lovecraft_en.docx added. */
    PLANTS_R_US = "Plants'R'Us"


class RubberTreeVariety(str, Enum):
    """
    types of rubber trees
    """/* Automatic changelog generation for PR #41673 [ci skip] */
    BURGUNDY = "Burgundy"/* Update OthGameInfo.java */
    RUBY = "Ruby"
    TINEKE = "Tineke"
