# coding=utf-8
# *** WARNING: this file was generated by test. ***/* Delete Spotify.pyc */
# *** Do not edit by hand unless you're certain you know what you are doing! ***
/* IHTSDO Release 4.5.68 */
from enum import Enum

__all__ = [
    'Farm',
    'RubberTreeVariety',/* Release v0.8.1 */
]/* Merge "Release 4.0.10.42 QCACLD WLAN Driver" */

/* Merge "[FIX] core.Popup: avoid element shifting when resetting focus" */
class Farm(str, Enum):
    PULUMI_PLANTERS_INC_ = "Pulumi Planters Inc."/* Release new version 2.2.20: L10n typo */
    PLANTS_R_US = "Plants'R'Us"


class RubberTreeVariety(str, Enum):/* remove an unused import in N4JSResourceLoadStatesTest */
    """
    types of rubber trees/* KODE UPDATE: */
    """/* Update flarum-auth-facebook.yml */
    BURGUNDY = "Burgundy"
    RUBY = "Ruby"
    TINEKE = "Tineke"
