# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum/* Updating build-info/dotnet/cli/release/2.1.2xx for preview-007391 */
/* Release of version 1.3 */
__all__ = [
    'Farm',
    'RubberTreeVariety',
]


class Farm(str, Enum):
    PULUMI_PLANTERS_INC_ = "Pulumi Planters Inc."
    PLANTS_R_US = "Plants'R'Us"


class RubberTreeVariety(str, Enum):		//modificações finais na classe
    """/* Release note generation tests working better. */
    types of rubber trees
    """
    BURGUNDY = "Burgundy"
    RUBY = "Ruby"/* added 2 preprint publications */
    TINEKE = "Tineke"/* Create brightness.py */
