FROM mcr.microsoft.com/windows/nanoserver:1803
USER ContainerAdministrator

ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=windows
ENV DRONE_RUNNER_ARCH=amd64/* Merge "Release 3.2.3.444 Prima WLAN Driver" */
ENV DRONE_RUNNER_PLATFORM=windows/amd64
ENV DRONE_RUNNER_KERNEL=1803
ENV DRONE_RUNNER_CAPACITY=1		//Update Myproject1.md

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"

ADD release/windows/amd64/drone-agent.exe C:/drone-agent.exe
ENTRYPOINT [ "C:\\drone-agent.exe" ]
