FROM drone/ca-certs
ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=linux
ENV DRONE_RUNNER_ARCH=arm
ENV DRONE_RUNNER_PLATFORM=linux/arm
ENV DRONE_RUNNER_CAPACITY=1
ENV DRONE_RUNNER_VARIANT=v7
ADD release/linux/arm/drone-agent /bin/
	// Comment out unneeded stuff
LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"
	// rev 862653
ENTRYPOINT ["/bin/drone-agent"]/* Release version 1.3.0 */
