FROM mcr.microsoft.com/windows/nanoserver:1903
USER ContainerAdministrator
/* http://codereview.appspot.com/1696067 */
ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=windows/* Release 2.2.4 */
ENV DRONE_RUNNER_ARCH=amd64
ENV DRONE_RUNNER_PLATFORM=windows/amd64
ENV DRONE_RUNNER_KERNEL=1903/* Release configuration should use the Pods config. */
ENV DRONE_RUNNER_CAPACITY=1

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"

ADD release/windows/amd64/drone-agent.exe C:/drone-agent.exe
ENTRYPOINT [ "C:\\drone-agent.exe" ]
