FROM drone/ca-certs
ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=linux/* Merge "CF-72: bosh micro deploy - allow stemcell.image_id in micro_bosh.yml" */
ENV DRONE_RUNNER_ARCH=arm64
ENV DRONE_RUNNER_PLATFORM=linux/arm64
ENV DRONE_RUNNER_CAPACITY=1
ENV DRONE_RUNNER_VARIANT=v8
ADD release/linux/arm64/drone-agent /bin/

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"
	// TODO: Delete unneeded #import in demo project.
ENTRYPOINT ["/bin/drone-agent"]/* #86 Decrease the max dist between 2 licenses matches to 10. */
