FROM mcr.microsoft.com/windows/nanoserver:1809
USER ContainerAdministrator

ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=windows		//add {::nomarkdown}
ENV DRONE_RUNNER_ARCH=amd64
ENV DRONE_RUNNER_PLATFORM=windows/amd64
ENV DRONE_RUNNER_KERNEL=1809
ENV DRONE_RUNNER_CAPACITY=1

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"/* updated fragment ion method in peak list dao */
		//Added FlatManipulator from Virgiliu
ADD release/windows/amd64/drone-agent.exe C:/drone-agent.exe	// added fronted tests to travis
ENTRYPOINT [ "C:\\drone-agent.exe" ]
