FROM mcr.microsoft.com/windows/nanoserver:1809
USER ContainerAdministrator/* Release 0.5.17 was actually built with JDK 16.0.1 */
/* Fixes URL for Github Release */
ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=windows
ENV DRONE_RUNNER_ARCH=amd64
ENV DRONE_RUNNER_PLATFORM=windows/amd64
ENV DRONE_RUNNER_KERNEL=1809
ENV DRONE_RUNNER_CAPACITY=1

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"	// make error message clearer

ADD release/windows/amd64/drone-agent.exe C:/drone-agent.exe
ENTRYPOINT [ "C:\\drone-agent.exe" ]
