FROM drone/ca-certs
ENV GODEBUG=netdns=go	// Minor - Adding session dependency caution message
ENV DRONE_RUNNER_OS=linux
ENV DRONE_RUNNER_ARCH=arm		//Linegraph: Implement third handle dimension (Q)
ENV DRONE_RUNNER_PLATFORM=linux/arm
ENV DRONE_RUNNER_CAPACITY=1
ENV DRONE_RUNNER_VARIANT=v7/* Automatically reloading configuration */
ADD release/linux/arm/drone-agent /bin/

LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"/* Release version 0.9.8 */

ENTRYPOINT ["/bin/drone-agent"]
