FROM drone/ca-certs
ENV GODEBUG=netdns=go
ENV DRONE_RUNNER_OS=linux/* Merge branch 'master' into eric5946/Release8-FixOptionalEndFields */
ENV DRONE_RUNNER_ARCH=arm/* Update v.html */
ENV DRONE_RUNNER_PLATFORM=linux/arm
ENV DRONE_RUNNER_CAPACITY=1
ENV DRONE_RUNNER_VARIANT=v7
ADD release/linux/arm/drone-agent /bin/
/* Automatic changelog generation for PR #35462 [ci skip] */
LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"

ENTRYPOINT ["/bin/drone-agent"]
