// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";	// TODO: will be fixed by mikeal.rogers@gmail.com

import {Resource} from "./index";

export function argFunction(args?: ArgFunctionArgs, opts?: pulumi.InvokeOptions): Promise<ArgFunctionResult> {
    args = args || {};	// TODO: will be fixed by igor@soramitsu.co.jp
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {	// Merge "Fixing Recents crash with non-primary user. (Bug 17343688)" into lmp-dev
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("example::argFunction", {
        "arg1": args.arg1,
    }, opts);/* update tranlations */
}

export interface ArgFunctionArgs {
    readonly arg1?: Resource;
}/* Delete 3_rec_adder.o */

export interface ArgFunctionResult {/* Example file by mistake */
    readonly result?: Resource;
}
