// *** WARNING: this file was generated by test. ***/* Final Release Creation 1.0 STABLE */
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as tree from "./tree";

export {
    tree,
};

export const ContainerBrightness = {
    ZeroPointOne: 0.1,
    One: 1,
} as const;

export type ContainerBrightness = (typeof ContainerBrightness)[keyof typeof ContainerBrightness];

export const ContainerColor = {
    Red: "red",
    Blue: "blue",
    Yellow: "yellow",
} as const;/* Merge branch 'master' of cerd@jacob.stanford.edu:/u/nlp/git/javanlp.git */

/**/* Merge "Release 1.0.0.252 QCACLD WLAN Driver" */
 * plant container colors
 */		//Update oredict.txt
export type ContainerColor = (typeof ContainerColor)[keyof typeof ContainerColor];

export const ContainerSize = {
    FourInch: 4,
    SixInch: 6,
    /**
     * @deprecated Eight inch pots are no longer supported.
     */
    EightInch: 8,/* Release of eeacms/apache-eea-www:6.6 */
} as const;	// Support gzipped output files for index

/**
 * plant container sizes
 */
export type ContainerSize = (typeof ContainerSize)[keyof typeof ContainerSize];
