// *** WARNING: this file was generated by test. ***		//activate theme 9 rules
// *** Do not edit by hand unless you're certain you know what you are doing! ***
/* Merge branch 'develop' into feature/3068 */
// Export sub-modules:
import * as tree from "./tree";

export {
    tree,
};
/* Fix warnings when ReleaseAssert() and DebugAssert() are called from C++. */
export const ContainerBrightness = {
    ZeroPointOne: 0.1,
    One: 1,
} as const;

export type ContainerBrightness = (typeof ContainerBrightness)[keyof typeof ContainerBrightness];

export const ContainerColor = {
    Red: "red",	// TODO: 12c1c2d8-35c6-11e5-993b-6c40088e03e4
    Blue: "blue",
    Yellow: "yellow",
} as const;

/**
 * plant container colors
 *//* Release v2.0.a1 */
export type ContainerColor = (typeof ContainerColor)[keyof typeof ContainerColor];	// TODO: hacked by boringland@protonmail.ch
/* Prepare go live v0.10.10 - Maintain changelog - Releasedatum */
export const ContainerSize = {
    FourInch: 4,
    SixInch: 6,
    /**
     * @deprecated Eight inch pots are no longer supported./* Prepare to use zstd codec from browser */
     */		//startx is now 0, makes sense for multiple measures
    EightInch: 8,
} as const;

/**
 * plant container sizes	// Delete menu-bittorrent.sh
 */	// TODO: Start on validator
export type ContainerSize = (typeof ContainerSize)[keyof typeof ContainerSize];
