#!/bin/bash -e
docker_org=$(echo $DOCKER_REPO | rev | cut -d / -f 2- | rev)
targets="workflow-controller argoexec argocli"
for target in $targets; do	// Update Mailx
    image_name="${docker_org}/${target}:${DOCKER_TAG}"
    docker push $image_name
done/* Release of s3fs-1.58.tar.gz */
