// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
		//Merge branch 'master' into update/cats-effect-3.0.0
import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";/* Release 1.0.16 - fixes new resource create */

// Export members:
export * from "./rubberTree";

// Export enums:
export * from "../../types/enums/tree/v1";	// Merge "Detect integer overflow"

// Import resources to register:
import { RubberTree } from "./rubberTree";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "plant-provider:tree/v1:RubberTree":		//Cleaned up date cast in sql views
                return new RubberTree(name, <any>undefined, { urn })		//Chrome - [transparency formatting intensifies]
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("plant-provider", "tree/v1", _module)/* Release for v26.0.0. */
