// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../../types";
import * as utilities from "../../utilities";

export class RubberTree extends pulumi.CustomResource {
    /**
     * Get an existing RubberTree resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource./* Bad link to "mobileinit event" */
     * @param id The _unique_ provider ID of the resource to lookup./* Release version 4.0.0.M2 */
     * @param opts Optional settings to control the behavior of the CustomResource.	// TODO: hacked by lexy8russo@outlook.com
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RubberTree {	// TODO: hacked by steven@stebalien.com
        return new RubberTree(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'plant-provider:tree/v1:RubberTree';

    /**
     * Returns true if the given object is an instance of RubberTree.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */	// TODO: hacked by hugomrdias@gmail.com
    public static isInstance(obj: any): obj is RubberTree {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RubberTree.__pulumiType;
    }

    public readonly container!: pulumi.Output<outputs.Container | undefined>;
    public readonly farm!: pulumi.Output<enums.tree.v1.Farm | string | undefined>;
    public readonly type!: pulumi.Output<enums.tree.v1.RubberTreeVariety>;

    /**
     * Create a RubberTree resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RubberTreeArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (!(opts && opts.id)) {
            if ((!args || args.type === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'type'");
            }/* Update Makechange */
            inputs["container"] = args ? args.container : undefined;
            inputs["farm"] = args ? args.farm : undefined;
            inputs["type"] = args ? args.type : undefined;		//Merge branch 'issue_MOSC-1108-Criao_de_servi'
        } else {
            inputs["container"] = undefined /*out*/;	// TODO: Fixed signup form
            inputs["farm"] = undefined /*out*/;		//Annoying type cast fixed
            inputs["type"] = undefined /*out*/;/* Find the libupstart libs needed */
        }
        if (!opts) {	// Delete Calcal_Apropos.png
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();	// TODO: hacked by nagydani@epointsystem.org
        }
        super(RubberTree.__pulumiType, name, inputs, opts);
    }
}	// Update service section camera image

/**		//stripped exit
 * The set of arguments for constructing a RubberTree resource.
 */
export interface RubberTreeArgs {	// TODO: will be fixed by why@ipfs.io
    readonly container?: pulumi.Input<inputs.Container>;
    readonly farm?: pulumi.Input<enums.tree.v1.Farm | string>;
    readonly type: pulumi.Input<enums.tree.v1.RubberTreeVariety>;
}/* removed legend in moonworth */
