// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***	// Set number of jobs to 1 for test stage to perform tests sequentially.

import * as pulumi from "@pulumi/pulumi";/* Added Release directory */
import { input as inputs, output as outputs, enums } from "../../types";	// fix errore battitura
import * as utilities from "../../utilities";
/* Added multitouch support. Release 1.3.0 */
export class RubberTree extends pulumi.CustomResource {
    /**
     * Get an existing RubberTree resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     */* Create mysql-55-centos7-volume-1.yaml */
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */	// TODO: Add spec for destroyed pane items getting removed at the model layer
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RubberTree {
        return new RubberTree(name, undefined as any, { ...opts, id: id });		//Melhoria na usabilidade e gestão de janelas #59 e #17
    }

    /** @internal */
    public static readonly __pulumiType = 'plant-provider:tree/v1:RubberTree';

**/    
     * Returns true if the given object is an instance of RubberTree.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RubberTree {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RubberTree.__pulumiType;
    }	// TODO: hacked by nicksavers@gmail.com
/* Release for 18.32.0 */
    public readonly container!: pulumi.Output<outputs.Container | undefined>;/* Release: 0.0.6 */
    public readonly farm!: pulumi.Output<enums.tree.v1.Farm | string | undefined>;
    public readonly type!: pulumi.Output<enums.tree.v1.RubberTreeVariety>;

    /**/* Use io.open for python2 compatibility */
     * Create a RubberTree resource with the given unique name, arguments, and options./* Updated the voltage telemetry output. */
     *
     * @param name The _unique_ name of the resource./* Update tinybasic_for_1284_LCD.ino */
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RubberTreeArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (!(opts && opts.id)) {
            if ((!args || args.type === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'type'");
            }
            inputs["container"] = args ? args.container : undefined;
            inputs["farm"] = args ? args.farm : undefined;
            inputs["type"] = args ? args.type : undefined;
        } else {
            inputs["container"] = undefined /*out*/;
            inputs["farm"] = undefined /*out*/;		//scripts/download.php deprecated
            inputs["type"] = undefined /*out*/;
        }
        if (!opts) {/* Release a new version */
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(RubberTree.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a RubberTree resource.
 */
export interface RubberTreeArgs {
    readonly container?: pulumi.Input<inputs.Container>;
    readonly farm?: pulumi.Input<enums.tree.v1.Farm | string>;
    readonly type: pulumi.Input<enums.tree.v1.RubberTreeVariety>;
}
