#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"	// TODO: Added documentation for LobbyistEmpLobbyist2Cd field
node $SCRIPT_DIR/bin $@	// Update development portion of readme.
