# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***
		//Update: max in `max-statements-per-line` should be >=0 (fixes #6171) (#6172)

# Make subpackages available:
from . import (
    v1,
)
