# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***


# Make subpackages available:
from . import (
    v1,	// First question added
)	// TODO: hacked by why@ipfs.io
