// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***		//Suggesting New Location: Daily Organics

using System;	// TODO: will be fixed by cory@protocol.ai
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;/* Merge "Fix wrong version of pip used in bootstrap" */
using Pulumi.Serialization;

namespace Pulumi.PlantProvider.Outputs
{

    [OutputType]		//349c6642-2e62-11e5-9284-b827eb9e62be
    public sealed class Container
    {
        public readonly Pulumi.PlantProvider.ContainerBrightness? Brightness;
        public readonly string? Color;
        public readonly string? Material;
        public readonly Pulumi.PlantProvider.ContainerSize Size;

        [OutputConstructor]
        private Container(
            Pulumi.PlantProvider.ContainerBrightness? brightness,		//Started Java grammar. Identifiers and keywords

            string? color,
		//Merge "Update mistral tests"
            string? material,

            Pulumi.PlantProvider.ContainerSize size)
        {
            Brightness = brightness;
            Color = color;/* Ajout du graphique des requêtes */
            Material = material;
            Size = size;
        }
    }/* Release v0.0.14 */
}	// TODO: will be fixed by sjors@sprovoost.nl
