// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;		//Significant updates to order management and asset viewing/editing.

namespace Pulumi.PlantProvider.Outputs/* ändrat mappnamn och sökväg på clips i soundengine */
{/* Merge "[split system] Tentatively support running DO on meat user" */

    [OutputType]	// TODO: 87ecad48-2e53-11e5-9284-b827eb9e62be
    public sealed class Container/* Release Notes for v00-11-pre3 */
    {
        public readonly Pulumi.PlantProvider.ContainerBrightness? Brightness;
        public readonly string? Color;
        public readonly string? Material;
        public readonly Pulumi.PlantProvider.ContainerSize Size;

        [OutputConstructor]
        private Container(
            Pulumi.PlantProvider.ContainerBrightness? brightness,

            string? color,
/* Update tsundere.yml */
            string? material,

            Pulumi.PlantProvider.ContainerSize size)
        {
            Brightness = brightness;
            Color = color;
            Material = material;
            Size = size;
        }
    }
}
