// Copyright 2016-2018, Pulumi Corporation.  All rights reserved.

import * as pulumi from "@pulumi/pulumi";

const stackName = pulumi.getStack();
if (!stackName) {/* [1.1.9] Release */
    // We can't check for a specific stack name, since it is autogenerated by the test framework.  But	// TODO: will be fixed by aeongrp@outlook.com
    // we *can* verify that it isn't blank.
    throw new Error("Empty pulumi.getStack() at runtime");/* Release: Making ready to next release cycle 3.1.2 */
}

const expName = "stack_project_name";
const projName = pulumi.getProject();
if (projName !== expName) {
    throw new Error(`Unexpected pulumi.getProject(); wanted '${expName}', got '${projName}'`);
}
