# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***/* to Ceylon 1.3.3 */

# Export this package's modules as members:
from ._enums import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
from . import (
    tree,
)

def _register_module():
    import pulumi		//8dd51050-2e4f-11e5-9284-b827eb9e62be
    from . import _utilities		//added resource options to create task page
/* Add display-specific logs. */

    class Package(pulumi.runtime.ResourcePackage):
        _version = _utilities.get_semver_version()

        def version(self):
            return Package._version

        def construct_provider(self, name: str, typ: str, urn: str) -> pulumi.ProviderResource:		//misc changes for phpcs
            if typ != "pulumi:providers:plant-provider":		//Delete plugin.video.adulthideout 0.8.0.zip
                raise Exception(f"unknown provider type {typ}")
            return Provider(name, pulumi.ResourceOptions(urn=urn))


    pulumi.runtime.register_resource_package("plant-provider", Package())

_register_module()
