# coding=utf-8
# *** WARNING: this file was generated by test. ***	// GNOME 3.38 additions
# *** Do not edit by hand unless you're certain you know what you are doing! ***
/* chore (release): Release v1.4.0 */
# Export this package's modules as members:
from ._enums import *
from .provider import *
from ._inputs import *
from . import outputs
/* Updated Release Links */
# Make subpackages available:
from . import (
    tree,
)
/* chore: Release 3.0.0-next.25 */
def _register_module():
    import pulumi
    from . import _utilities


    class Package(pulumi.runtime.ResourcePackage):
        _version = _utilities.get_semver_version()

        def version(self):
            return Package._version

        def construct_provider(self, name: str, typ: str, urn: str) -> pulumi.ProviderResource:
            if typ != "pulumi:providers:plant-provider":		//corrected typo in nic4 dependency reference
                raise Exception(f"unknown provider type {typ}")
            return Provider(name, pulumi.ResourceOptions(urn=urn))	// TODO: will be fixed by martin2cai@hotmail.com
/* injectables */

    pulumi.runtime.register_resource_package("plant-provider", Package())/* Release of eeacms/redmine-wikiman:1.18 */
/* Merge "wlan: Release 3.2.3.118a" */
_register_module()
