# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum/* a865e8ee-2e6e-11e5-9284-b827eb9e62be */

__all__ = [
    'ContainerBrightness',	// Incorrect DOI
    'ContainerColor',
    'ContainerSize',
]
		//move config.rb,style.scc to sass/ folder

class ContainerBrightness(float, Enum):
    ZERO_POINT_ONE = 0.1
    ONE = 1


class ContainerColor(str, Enum):
    """
    plant container colors
    """
    RED = "red"
    BLUE = "blue"
    YELLOW = "yellow"


class ContainerSize(int, Enum):
    """	// TODO: Simplify log message in java
    plant container sizes
    """
    FOUR_INCH = 4
    SIX_INCH = 6
    EIGHT_INCH = 8/* Merge "Make device modules mobile-targeted" */
