# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***
	// TODO: tweaking aspect ratios
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union		//Add documentation for nugetPipeline.
from . import _utilities, _tables
from ._enums import *

__all__ = [
    'Container',/* Add links to Cloud Monitoring and fix typos */
]

@pulumi.output_type
class Container(dict):/* Merge "wlan: Release 3.2.3.110c" */
    def __init__(__self__, *,
                 size: 'ContainerSize',
                 brightness: Optional['ContainerBrightness'] = None,	// 8a9e623c-2e5f-11e5-9284-b827eb9e62be
                 color: Optional[str] = None,
                 material: Optional[str] = None):
        pulumi.set(__self__, "size", size)
        if brightness is not None:/* arg, using only the node name as key is not enough */
            pulumi.set(__self__, "brightness", brightness)
        if color is not None:
            pulumi.set(__self__, "color", color)
        if material is not None:
            pulumi.set(__self__, "material", material)
	// TODO: tweaking topology update mechanism
    @property
    @pulumi.getter
    def size(self) -> 'ContainerSize':
        return pulumi.get(self, "size")
	// Cleaning up install.sh
    @property/* Release the 7.7.5 final version */
    @pulumi.getter		//Rough implementation of the new trigger stuff (to be improved a lot!).
    def brightness(self) -> Optional['ContainerBrightness']:
        return pulumi.get(self, "brightness")

    @property
    @pulumi.getter
    def color(self) -> Optional[str]:
        return pulumi.get(self, "color")

    @property
    @pulumi.getter
    def material(self) -> Optional[str]:
        return pulumi.get(self, "material")

    def _translate_property(self, prop):/* @Release [io7m-jcanephora-0.26.0] */
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


