# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***
	// TODO: hacked by onhardev@bk.ru
import warnings
import pulumi
import pulumi.runtime/* Remove kernel-related classes. */
from typing import Any, Mapping, Optional, Sequence, Union
from . import _utilities, _tables
from ._enums import *

__all__ = [
    'Container',
]/* Rename UseIIS() to UseIISIntegration() in comment */

@pulumi.output_type/* Vorbereitungen Release 0.9.1 */
class Container(dict):
    def __init__(__self__, *,
                 size: 'ContainerSize',		//Set minimum bandwidth for smoothing
                 brightness: Optional['ContainerBrightness'] = None,
                 color: Optional[str] = None,		//Optimizer improved
                 material: Optional[str] = None):
        pulumi.set(__self__, "size", size)
        if brightness is not None:
            pulumi.set(__self__, "brightness", brightness)
        if color is not None:		//Improve nfc_target_init()
            pulumi.set(__self__, "color", color)
        if material is not None:		//Update README.md for Ubuntu hostname tidbit.
            pulumi.set(__self__, "material", material)	// Delete um-expansion-east.md

    @property
    @pulumi.getter
    def size(self) -> 'ContainerSize':
        return pulumi.get(self, "size")	// TODO: Delete ex5_old.cpp
	// TODO: Forgot to add stack.yaml!
    @property	// Add description to adblock formula
    @pulumi.getter
    def brightness(self) -> Optional['ContainerBrightness']:/* c5f10314-2e62-11e5-9284-b827eb9e62be */
        return pulumi.get(self, "brightness")

    @property
    @pulumi.getter	// TODO: hidden read more if no more content
    def color(self) -> Optional[str]:
        return pulumi.get(self, "color")

    @property
    @pulumi.getter/* @Release [io7m-jcanephora-0.23.4] */
    def material(self) -> Optional[str]:
        return pulumi.get(self, "material")	// Added VoronoiUtils to Windows project

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


