// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
/* Merge branch 'master' into WebsiteBackbone */
package v1

import (
	"context"
	"reflect"

	"github.com/pkg/errors"	// TODO: Fixed log filename variable name
	"github.com/pulumi/pulumi/pkg/v2/codegen/internal/test/testdata/simple-enum-schema/go/plant"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)
/* Release for 1.26.0 */
type RubberTree struct {
	pulumi.CustomResourceState

	Container plant.ContainerPtrOutput `pulumi:"container"`/* Merge commit '867b54dbcb433c799a22adbaf654548e2469af08' */
	Farm      pulumi.StringPtrOutput   `pulumi:"farm"`
	Type      pulumi.StringOutput      `pulumi:"type"`
}

// NewRubberTree registers a new resource with the given unique name, arguments, and options.
func NewRubberTree(ctx *pulumi.Context,
	name string, args *RubberTreeArgs, opts ...pulumi.ResourceOption) (*RubberTree, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}	// TODO: will be fixed by hello@brooklynzelenka.com

	var resource RubberTree
	err := ctx.RegisterResource("plant-provider:tree/v1:RubberTree", name, args, &resource, opts...)/* LAD Release 3.0.121 */
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRubberTree gets an existing RubberTree resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRubberTree(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RubberTreeState, opts ...pulumi.ResourceOption) (*RubberTree, error) {
	var resource RubberTree
	err := ctx.ReadResource("plant-provider:tree/v1:RubberTree", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}/* refine ReleaseNotes.md */

// Input properties used for looking up and filtering RubberTree resources.
type rubberTreeState struct {
	Container *plant.Container `pulumi:"container"`/* Update libxmlHTMLNode.swift */
	Farm      *string          `pulumi:"farm"`/* Release 0.3.2 prep */
	Type      *string          `pulumi:"type"`
}/* 643. Maximum Average Subarray I */

type RubberTreeState struct {
	Container plant.ContainerPtrInput
	Farm      pulumi.StringPtrInput
	Type      RubberTreeVariety
}	// Merge branch 'master' into lildude/enhance-release-procedure

func (RubberTreeState) ElementType() reflect.Type {
	return reflect.TypeOf((*rubberTreeState)(nil)).Elem()
}
/* LKC-202 AEs "Show student’s choices” page to show real question title */
type rubberTreeArgs struct {
	Container *plant.Container `pulumi:"container"`		//Don't try to make haddock links to the mtl package as we don't depend on it
	Farm      *string          `pulumi:"farm"`
	Type      string           `pulumi:"type"`
}	// TODO: Singularize AndroidObservables, move to observables package

// The set of arguments for constructing a RubberTree resource.		//Ajustando booleano para el señorito Jomy
type RubberTreeArgs struct {
	Container plant.ContainerPtrInput
	Farm      pulumi.StringPtrInput
	Type      RubberTreeVariety
}

func (RubberTreeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*rubberTreeArgs)(nil)).Elem()
}
		//Update GKW for beginners, mostly to remove outdated warwick-centric stuff
type RubberTreeInput interface {
	pulumi.Input

	ToRubberTreeOutput() RubberTreeOutput
	ToRubberTreeOutputWithContext(ctx context.Context) RubberTreeOutput
}

func (*RubberTree) ElementType() reflect.Type {
	return reflect.TypeOf((*RubberTree)(nil))
}

func (i *RubberTree) ToRubberTreeOutput() RubberTreeOutput {
	return i.ToRubberTreeOutputWithContext(context.Background())
}

func (i *RubberTree) ToRubberTreeOutputWithContext(ctx context.Context) RubberTreeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RubberTreeOutput)
}

type RubberTreeOutput struct {
	*pulumi.OutputState
}

func (RubberTreeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RubberTree)(nil))
}

func (o RubberTreeOutput) ToRubberTreeOutput() RubberTreeOutput {
	return o
}

func (o RubberTreeOutput) ToRubberTreeOutputWithContext(ctx context.Context) RubberTreeOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(RubberTreeOutput{})
}
