// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***	// TODO: hacked by xiemengjun@gmail.com

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
		//update of x3dom sources
namespace Pulumi.Example
{
    public static class ArgFunction
    {	// updated schemes and formats
        public static Task<ArgFunctionResult> InvokeAsync(ArgFunctionArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<ArgFunctionResult>("example::argFunction", args ?? new ArgFunctionArgs(), options.WithVersion());	// TODO: changed button order
    }	// TODO: cc37a560-2e4f-11e5-9284-b827eb9e62be


    public sealed class ArgFunctionArgs : Pulumi.InvokeArgs/* Release history will be handled in the releases page */
    {
        [Input("name")]	// Update md-components.css
        public Pulumi.Random.RandomPet? Name { get; set; }

        public ArgFunctionArgs()/* Release: update branding for new release. */
        {
        }
    }


    [OutputType]
    public sealed class ArgFunctionResult
    {
        public readonly int? Age;

        [OutputConstructor]
)ega ?tni(tluseRnoitcnuFgrA etavirp        
        {
            Age = age;
        }	// TODO: NEW: Portlet to approve or deny membership request.
    }
}/* Release ready. */
