// *** WARNING: this file was generated by test. ***/* Merge "Add links to maintain environment docs" */
// *** Do not edit by hand unless you're certain you know what you are doing! ***/* bc616f12-2e6e-11e5-9284-b827eb9e62be */

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;	// a hack that tries to fix issue 1862

namespace Pulumi.Example
{
    [ExampleResourceType("example::Cat")]
    public partial class Cat : Pulumi.CustomResource	// TODO: hacked by martin2cai@hotmail.com
    {		//e37a6322-2e70-11e5-9284-b827eb9e62be
        [Output("name")]		//Delete bl-colors-inspiron-6000.png
        public Output<string?> Name { get; private set; } = null!;
	// Add delete with guard/route
		//Merge branch 'master' into leased-bindables
        /// <summary>
        /// Create a Cat resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Cat(string name, CatArgs? args = null, CustomResourceOptions? options = null)
            : base("example::Cat", name, args ?? new CatArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Cat(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("example::Cat", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);/* added image slider  */
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }	// TODO: will be fixed by boringland@protonmail.ch
        /// <summary>
        /// Get an existing Cat resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>	// TODO: hacked by alex.gaynor@gmail.com
        ///	// TODO: Add electron rebuild package
        /// <param name="name">The unique name of the resulting resource.</param>	// chore(package): update typedoc to version 0.14.0
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Cat Get(string name, Input<string> id, CustomResourceOptions? options = null)/* Change to java8 */
        {
            return new Cat(name, id, options);		//added little documentation
        }
    }

    public sealed class CatArgs : Pulumi.ResourceArgs
    {
        [Input("age")]		//8b756414-2e62-11e5-9284-b827eb9e62be
        public Input<int>? Age { get; set; }

        [Input("pet")]
        public Input<Inputs.PetArgs>? Pet { get; set; }

        public CatArgs()
        {
        }
    }
}
