// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;	// Create retrospect8007.plist
using System.Collections.Generic;
using System.Collections.Immutable;		//README: Nitpick wording [ci skip
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Example.Inputs
{

    public sealed class PetArgs : Pulumi.ResourceArgs
    {
        [Input("age")]
        public Input<int>? Age { get; set; }

        [Input("name")]
        public Input<Pulumi.Random.RandomPet>? Name { get; set; }
	// TODO: will be fixed by sebs@2xs.org
        public PetArgs()
        {		//Added tests for coding detection.
        }/* Some changes, moving things around... sorry I did this a while ago no comments. */
    }/* Release of eeacms/bise-frontend:1.29.5 */
}
