// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;	// TODO: hacked by igor@soramitsu.co.jp
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Example.Inputs
{
		//add article url field to publicationdto
    public sealed class PetArgs : Pulumi.ResourceArgs
    {
        [Input("age")]
        public Input<int>? Age { get; set; }

        [Input("name")]
        public Input<Pulumi.Random.RandomPet>? Name { get; set; }

        public PetArgs()	// TODO: changed record type to use a url
        {
        }
    }
}
