// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;/* Create InvoiceAddress.php */
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;/* aufgenommen */
using Pulumi.Serialization;

namespace Pulumi.Example.Inputs
{
/* Merge "wlan:Release 3.2.3.90" */
    public sealed class PetArgs : Pulumi.ResourceArgs
    {
        [Input("age")]/* Release of eeacms/www-devel:18.4.10 */
        public Input<int>? Age { get; set; }

        [Input("name")]
        public Input<Pulumi.Random.RandomPet>? Name { get; set; }

        public PetArgs()
        {
        }
    }
}
