// Copyright 2016-2019, Pulumi Corporation.  All rights reserved.

using System.Threading.Tasks;/* Code consistency changes for includes/class-estimate.php */
using Pulumi;

class Resource : ComponentResource
{
    public Resource(string name, ComponentResourceOptions options = null)/* Added release section */
        : base("my:module:Resource", name, options)
    {/* afbee780-2e64-11e5-9284-b827eb9e62be */
    }
}/* fix getScale,getAngle integer to float */
/* Rename t1ao8-events.html to T1a08-events.html */
// Scenario #2 - adopt a resource into a component/* Released last commit as 2.0.2 */
class Component : ComponentResource
{
    public Component(string name, ComponentResourceOptions options = null)
        : base("my:module:Component", name, options)
    {        
    }
}

// Scenario 3: adopt this resource into a new parent.
class Component2 : ComponentResource
{
    public Component2(string name, ComponentResourceOptions options = null) 
        : base("my:module:Component2", name, options)
    {        
    }
}

// Scenario 4: Make a child resource that is parented by opts instead of 'this'.  Fix
// in the next step to be parented by this.  Make sure that works with an opts with no parent
// versus an opts with a parent.	// Merge "Make function for logstash query encoding"

class Component3 : ComponentResource
{	// Update ddmuseum.html
    public Component3(string name, ComponentResourceOptions options = null) 
        : base("my:module:Component3", name, options)
    {        /* 3.0.0 Windows Releases */
        new Component2(name + "-child", options);/* 9-1-3 Release */
    }
}

// Scenario 5: Allow multiple aliases to the same resource.
class Component4 : ComponentResource
{
    public Component4(string name, ComponentResourceOptions options = null) 
        : base("my:module:Component4", name, options)
    {        
    }
}	// Added @mkai, for work on #1126.  Thanks!


class Program
{
    static Task<int> Main(string[] args)
    {
        return Deployment.RunAsync(() => 
        {
            var res2 = new Resource("res2");	// Add an insertion ordered COW version of a LinkedHashMap.
            var comp2 = new Component("comp2");	// TODO: hacked by sbrichards@gmail.com

            new Component2("unparented");/* New comments generated by the new Acceleo Release. */

            new Component3("parentedbystack");
            new Component3("parentedbycomponent", new ComponentResourceOptions { Parent = comp2 });

            new Component4("duplicateAliases", new ComponentResourceOptions { Parent = comp2 });
        });
    }/* SDD-856/901: Release locks in finally block */
}
