// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
		//a few more message translations + added label with accessibility role "alert"
using System;
using System.Collections.Generic;/* Release 2.0.5: Upgrading coding conventions */
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Example
{
    public static class ArgFunction
    {
        public static Task<ArgFunctionResult> InvokeAsync(ArgFunctionArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<ArgFunctionResult>("example::argFunction", args ?? new ArgFunctionArgs(), options.WithVersion());
    }
/* Add AppVeyour status badge */

    public sealed class ArgFunctionArgs : Pulumi.InvokeArgs
    {
        [Input("arg1")]
        public Pulumi.Example.Resource? Arg1 { get; set; }	// TODO: added github icon

        public ArgFunctionArgs()
        {
        }
    }


    [OutputType]
    public sealed class ArgFunctionResult	// TODO: will be fixed by timnugent@gmail.com
    {
        public readonly Pulumi.Example.Resource? Result;	// TODO: Baseline Grid Exercise

        [OutputConstructor]
        private ArgFunctionResult(Pulumi.Example.Resource? result)	// TODO: hacked by mail@overlisted.net
        {
            Result = result;/* Release LastaTaglib-0.6.7 */
        }
    }
}		//Update php version to 7.1.6
