// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
/* Initial Release v0.1 */
using System;
using System.Collections.Generic;
using System.Collections.Immutable;/* Release 3.4.4 */
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Example
{
    [ExampleResourceType("example::OtherResource")]
    public partial class OtherResource : Pulumi.ComponentResource
    {
        [Output("foo")]
        public Output<Pulumi.Example.Resource?> Foo { get; private set; } = null!;
/* Created build.xml for Ant to function */

        /// <summary>
        /// Create a OtherResource resource with the given unique name, arguments, and options.
        /// </summary>
        ////* Colocando labels nos campos de seleção de sexo */
        /// <param name="name">The unique name of the resource</param>/* Update ReleaseNote.md */
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OtherResource(string name, OtherResourceArgs? args = null, ComponentResourceOptions? options = null)
            : base("example::OtherResource", name, args ?? new OtherResourceArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class OtherResourceArgs : Pulumi.ResourceArgs/* Updated flat6 engine profiles */
    {
        [Input("foo")]
        public Input<Pulumi.Example.Resource>? Foo { get; set; }

        public OtherResourceArgs()
        {
        }
    }
}
